//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region Metadatos de relaciones en EDM

[assembly: EdmRelationshipAttribute("ClinicaAspModel", "FK__Cita__CedulaM__0DAF0CB0", "Medico", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Clinica_ASP.Medico), "Cita", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Clinica_ASP.Cita), true)]
[assembly: EdmRelationshipAttribute("ClinicaAspModel", "FK__Cita__CedulaPaci__0CBAE877", "Paciente", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Clinica_ASP.Paciente), "Cita", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Clinica_ASP.Cita), true)]
[assembly: EdmRelationshipAttribute("ClinicaAspModel", "FK__FormulaMe__IdCit__1273C1CD", "Cita", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Clinica_ASP.Cita), "FormulaMedica", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Clinica_ASP.FormulaMedica), true)]

#endregion

namespace Clinica_ASP
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class ClinicaAspEntities : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto ClinicaAspEntities usando la cadena de conexión encontrada en la sección 'ClinicaAspEntities' del archivo de configuración de la aplicación.
        /// </summary>
        public ClinicaAspEntities() : base("name=ClinicaAspEntities", "ClinicaAspEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto ClinicaAspEntities.
        /// </summary>
        public ClinicaAspEntities(string connectionString) : base(connectionString, "ClinicaAspEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto ClinicaAspEntities.
        /// </summary>
        public ClinicaAspEntities(EntityConnection connection) : base(connection, "ClinicaAspEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Cita> Citas
        {
            get
            {
                if ((_Citas == null))
                {
                    _Citas = base.CreateObjectSet<Cita>("Citas");
                }
                return _Citas;
            }
        }
        private ObjectSet<Cita> _Citas;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<FormulaMedica> FormulaMedicas
        {
            get
            {
                if ((_FormulaMedicas == null))
                {
                    _FormulaMedicas = base.CreateObjectSet<FormulaMedica>("FormulaMedicas");
                }
                return _FormulaMedicas;
            }
        }
        private ObjectSet<FormulaMedica> _FormulaMedicas;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Medico> Medicos
        {
            get
            {
                if ((_Medicos == null))
                {
                    _Medicos = base.CreateObjectSet<Medico>("Medicos");
                }
                return _Medicos;
            }
        }
        private ObjectSet<Medico> _Medicos;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Paciente> Pacientes
        {
            get
            {
                if ((_Pacientes == null))
                {
                    _Pacientes = base.CreateObjectSet<Paciente>("Pacientes");
                }
                return _Pacientes;
            }
        }
        private ObjectSet<Paciente> _Pacientes;

        #endregion

        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Citas. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToCitas(Cita cita)
        {
            base.AddObject("Citas", cita);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet FormulaMedicas. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToFormulaMedicas(FormulaMedica formulaMedica)
        {
            base.AddObject("FormulaMedicas", formulaMedica);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Medicos. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToMedicos(Medico medico)
        {
            base.AddObject("Medicos", medico);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Pacientes. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToPacientes(Paciente paciente)
        {
            base.AddObject("Pacientes", paciente);
        }

        #endregion

    }

    #endregion

    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ClinicaAspModel", Name="Cita")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Cita : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Cita.
        /// </summary>
        /// <param name="idCita">Valor inicial de la propiedad IdCita.</param>
        /// <param name="fechacita">Valor inicial de la propiedad fechacita.</param>
        /// <param name="horaCita">Valor inicial de la propiedad HoraCita.</param>
        public static Cita CreateCita(global::System.Int32 idCita, global::System.String fechacita, global::System.String horaCita)
        {
            Cita cita = new Cita();
            cita.IdCita = idCita;
            cita.fechacita = fechacita;
            cita.HoraCita = horaCita;
            return cita;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdCita
        {
            get
            {
                return _IdCita;
            }
            set
            {
                if (_IdCita != value)
                {
                    OnIdCitaChanging(value);
                    ReportPropertyChanging("IdCita");
                    _IdCita = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdCita");
                    OnIdCitaChanged();
                }
            }
        }
        private global::System.Int32 _IdCita;
        partial void OnIdCitaChanging(global::System.Int32 value);
        partial void OnIdCitaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CedulaPaciente
        {
            get
            {
                return _CedulaPaciente;
            }
            set
            {
                OnCedulaPacienteChanging(value);
                ReportPropertyChanging("CedulaPaciente");
                _CedulaPaciente = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CedulaPaciente");
                OnCedulaPacienteChanged();
            }
        }
        private Nullable<global::System.Int32> _CedulaPaciente;
        partial void OnCedulaPacienteChanging(Nullable<global::System.Int32> value);
        partial void OnCedulaPacienteChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CedulaM
        {
            get
            {
                return _CedulaM;
            }
            set
            {
                OnCedulaMChanging(value);
                ReportPropertyChanging("CedulaM");
                _CedulaM = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CedulaM");
                OnCedulaMChanged();
            }
        }
        private Nullable<global::System.Int32> _CedulaM;
        partial void OnCedulaMChanging(Nullable<global::System.Int32> value);
        partial void OnCedulaMChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String fechacita
        {
            get
            {
                return _fechacita;
            }
            set
            {
                OnfechacitaChanging(value);
                ReportPropertyChanging("fechacita");
                _fechacita = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("fechacita");
                OnfechacitaChanged();
            }
        }
        private global::System.String _fechacita;
        partial void OnfechacitaChanging(global::System.String value);
        partial void OnfechacitaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String HoraCita
        {
            get
            {
                return _HoraCita;
            }
            set
            {
                OnHoraCitaChanging(value);
                ReportPropertyChanging("HoraCita");
                _HoraCita = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("HoraCita");
                OnHoraCitaChanged();
            }
        }
        private global::System.String _HoraCita;
        partial void OnHoraCitaChanging(global::System.String value);
        partial void OnHoraCitaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Descripcion
        {
            get
            {
                return _Descripcion;
            }
            set
            {
                OnDescripcionChanging(value);
                ReportPropertyChanging("Descripcion");
                _Descripcion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Descripcion");
                OnDescripcionChanged();
            }
        }
        private global::System.String _Descripcion;
        partial void OnDescripcionChanging(global::System.String value);
        partial void OnDescripcionChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ClinicaAspModel", "FK__Cita__CedulaM__0DAF0CB0", "Medico")]
        public Medico Medico
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Medico>("ClinicaAspModel.FK__Cita__CedulaM__0DAF0CB0", "Medico").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Medico>("ClinicaAspModel.FK__Cita__CedulaM__0DAF0CB0", "Medico").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Medico> MedicoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Medico>("ClinicaAspModel.FK__Cita__CedulaM__0DAF0CB0", "Medico");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Medico>("ClinicaAspModel.FK__Cita__CedulaM__0DAF0CB0", "Medico", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ClinicaAspModel", "FK__Cita__CedulaPaci__0CBAE877", "Paciente")]
        public Paciente Paciente
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Paciente>("ClinicaAspModel.FK__Cita__CedulaPaci__0CBAE877", "Paciente").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Paciente>("ClinicaAspModel.FK__Cita__CedulaPaci__0CBAE877", "Paciente").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Paciente> PacienteReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Paciente>("ClinicaAspModel.FK__Cita__CedulaPaci__0CBAE877", "Paciente");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Paciente>("ClinicaAspModel.FK__Cita__CedulaPaci__0CBAE877", "Paciente", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ClinicaAspModel", "FK__FormulaMe__IdCit__1273C1CD", "FormulaMedica")]
        public EntityCollection<FormulaMedica> FormulaMedicas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<FormulaMedica>("ClinicaAspModel.FK__FormulaMe__IdCit__1273C1CD", "FormulaMedica");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<FormulaMedica>("ClinicaAspModel.FK__FormulaMe__IdCit__1273C1CD", "FormulaMedica", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ClinicaAspModel", Name="FormulaMedica")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class FormulaMedica : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto FormulaMedica.
        /// </summary>
        /// <param name="idFormulaMedica">Valor inicial de la propiedad IdFormulaMedica.</param>
        /// <param name="idCita">Valor inicial de la propiedad IdCita.</param>
        /// <param name="recetaMedica">Valor inicial de la propiedad RecetaMedica.</param>
        public static FormulaMedica CreateFormulaMedica(global::System.Int32 idFormulaMedica, global::System.Int32 idCita, global::System.String recetaMedica)
        {
            FormulaMedica formulaMedica = new FormulaMedica();
            formulaMedica.IdFormulaMedica = idFormulaMedica;
            formulaMedica.IdCita = idCita;
            formulaMedica.RecetaMedica = recetaMedica;
            return formulaMedica;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdFormulaMedica
        {
            get
            {
                return _IdFormulaMedica;
            }
            set
            {
                if (_IdFormulaMedica != value)
                {
                    OnIdFormulaMedicaChanging(value);
                    ReportPropertyChanging("IdFormulaMedica");
                    _IdFormulaMedica = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdFormulaMedica");
                    OnIdFormulaMedicaChanged();
                }
            }
        }
        private global::System.Int32 _IdFormulaMedica;
        partial void OnIdFormulaMedicaChanging(global::System.Int32 value);
        partial void OnIdFormulaMedicaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdCita
        {
            get
            {
                return _IdCita;
            }
            set
            {
                OnIdCitaChanging(value);
                ReportPropertyChanging("IdCita");
                _IdCita = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdCita");
                OnIdCitaChanged();
            }
        }
        private global::System.Int32 _IdCita;
        partial void OnIdCitaChanging(global::System.Int32 value);
        partial void OnIdCitaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RecetaMedica
        {
            get
            {
                return _RecetaMedica;
            }
            set
            {
                OnRecetaMedicaChanging(value);
                ReportPropertyChanging("RecetaMedica");
                _RecetaMedica = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("RecetaMedica");
                OnRecetaMedicaChanged();
            }
        }
        private global::System.String _RecetaMedica;
        partial void OnRecetaMedicaChanging(global::System.String value);
        partial void OnRecetaMedicaChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ClinicaAspModel", "FK__FormulaMe__IdCit__1273C1CD", "Cita")]
        public Cita Cita
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cita>("ClinicaAspModel.FK__FormulaMe__IdCit__1273C1CD", "Cita").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cita>("ClinicaAspModel.FK__FormulaMe__IdCit__1273C1CD", "Cita").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Cita> CitaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cita>("ClinicaAspModel.FK__FormulaMe__IdCit__1273C1CD", "Cita");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Cita>("ClinicaAspModel.FK__FormulaMe__IdCit__1273C1CD", "Cita", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ClinicaAspModel", Name="Medico")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Medico : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Medico.
        /// </summary>
        /// <param name="cedulaM">Valor inicial de la propiedad CedulaM.</param>
        /// <param name="nombreM">Valor inicial de la propiedad NombreM.</param>
        /// <param name="apellidoM">Valor inicial de la propiedad ApellidoM.</param>
        /// <param name="emailM">Valor inicial de la propiedad EmailM.</param>
        /// <param name="contrasena">Valor inicial de la propiedad contrasena.</param>
        /// <param name="anionacimiento">Valor inicial de la propiedad anionacimiento.</param>
        /// <param name="especialidad">Valor inicial de la propiedad Especialidad.</param>
        public static Medico CreateMedico(global::System.Int32 cedulaM, global::System.String nombreM, global::System.String apellidoM, global::System.String emailM, global::System.String contrasena, global::System.DateTime anionacimiento, global::System.String especialidad)
        {
            Medico medico = new Medico();
            medico.CedulaM = cedulaM;
            medico.NombreM = nombreM;
            medico.ApellidoM = apellidoM;
            medico.EmailM = emailM;
            medico.contrasena = contrasena;
            medico.anionacimiento = anionacimiento;
            medico.Especialidad = especialidad;
            return medico;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CedulaM
        {
            get
            {
                return _CedulaM;
            }
            set
            {
                if (_CedulaM != value)
                {
                    OnCedulaMChanging(value);
                    ReportPropertyChanging("CedulaM");
                    _CedulaM = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CedulaM");
                    OnCedulaMChanged();
                }
            }
        }
        private global::System.Int32 _CedulaM;
        partial void OnCedulaMChanging(global::System.Int32 value);
        partial void OnCedulaMChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NombreM
        {
            get
            {
                return _NombreM;
            }
            set
            {
                OnNombreMChanging(value);
                ReportPropertyChanging("NombreM");
                _NombreM = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NombreM");
                OnNombreMChanged();
            }
        }
        private global::System.String _NombreM;
        partial void OnNombreMChanging(global::System.String value);
        partial void OnNombreMChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ApellidoM
        {
            get
            {
                return _ApellidoM;
            }
            set
            {
                OnApellidoMChanging(value);
                ReportPropertyChanging("ApellidoM");
                _ApellidoM = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ApellidoM");
                OnApellidoMChanged();
            }
        }
        private global::System.String _ApellidoM;
        partial void OnApellidoMChanging(global::System.String value);
        partial void OnApellidoMChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EmailM
        {
            get
            {
                return _EmailM;
            }
            set
            {
                OnEmailMChanging(value);
                ReportPropertyChanging("EmailM");
                _EmailM = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("EmailM");
                OnEmailMChanged();
            }
        }
        private global::System.String _EmailM;
        partial void OnEmailMChanging(global::System.String value);
        partial void OnEmailMChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String contrasena
        {
            get
            {
                return _contrasena;
            }
            set
            {
                OncontrasenaChanging(value);
                ReportPropertyChanging("contrasena");
                _contrasena = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("contrasena");
                OncontrasenaChanged();
            }
        }
        private global::System.String _contrasena;
        partial void OncontrasenaChanging(global::System.String value);
        partial void OncontrasenaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime anionacimiento
        {
            get
            {
                return _anionacimiento;
            }
            set
            {
                OnanionacimientoChanging(value);
                ReportPropertyChanging("anionacimiento");
                _anionacimiento = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("anionacimiento");
                OnanionacimientoChanged();
            }
        }
        private global::System.DateTime _anionacimiento;
        partial void OnanionacimientoChanging(global::System.DateTime value);
        partial void OnanionacimientoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> telefono
        {
            get
            {
                return _telefono;
            }
            set
            {
                OntelefonoChanging(value);
                ReportPropertyChanging("telefono");
                _telefono = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("telefono");
                OntelefonoChanged();
            }
        }
        private Nullable<global::System.Int32> _telefono;
        partial void OntelefonoChanging(Nullable<global::System.Int32> value);
        partial void OntelefonoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Especialidad
        {
            get
            {
                return _Especialidad;
            }
            set
            {
                OnEspecialidadChanging(value);
                ReportPropertyChanging("Especialidad");
                _Especialidad = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Especialidad");
                OnEspecialidadChanged();
            }
        }
        private global::System.String _Especialidad;
        partial void OnEspecialidadChanging(global::System.String value);
        partial void OnEspecialidadChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ClinicaAspModel", "FK__Cita__CedulaM__0DAF0CB0", "Cita")]
        public EntityCollection<Cita> Citas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Cita>("ClinicaAspModel.FK__Cita__CedulaM__0DAF0CB0", "Cita");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Cita>("ClinicaAspModel.FK__Cita__CedulaM__0DAF0CB0", "Cita", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ClinicaAspModel", Name="Paciente")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Paciente : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Paciente.
        /// </summary>
        /// <param name="cedulaPaciente">Valor inicial de la propiedad CedulaPaciente.</param>
        /// <param name="nombrePaciente">Valor inicial de la propiedad NombrePaciente.</param>
        /// <param name="apellidoPaciente">Valor inicial de la propiedad ApellidoPaciente.</param>
        /// <param name="email">Valor inicial de la propiedad Email.</param>
        /// <param name="contrasena">Valor inicial de la propiedad contrasena.</param>
        /// <param name="anionacimiento">Valor inicial de la propiedad anionacimiento.</param>
        public static Paciente CreatePaciente(global::System.Int32 cedulaPaciente, global::System.String nombrePaciente, global::System.String apellidoPaciente, global::System.String email, global::System.String contrasena, global::System.DateTime anionacimiento)
        {
            Paciente paciente = new Paciente();
            paciente.CedulaPaciente = cedulaPaciente;
            paciente.NombrePaciente = nombrePaciente;
            paciente.ApellidoPaciente = apellidoPaciente;
            paciente.Email = email;
            paciente.contrasena = contrasena;
            paciente.anionacimiento = anionacimiento;
            return paciente;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CedulaPaciente
        {
            get
            {
                return _CedulaPaciente;
            }
            set
            {
                if (_CedulaPaciente != value)
                {
                    OnCedulaPacienteChanging(value);
                    ReportPropertyChanging("CedulaPaciente");
                    _CedulaPaciente = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CedulaPaciente");
                    OnCedulaPacienteChanged();
                }
            }
        }
        private global::System.Int32 _CedulaPaciente;
        partial void OnCedulaPacienteChanging(global::System.Int32 value);
        partial void OnCedulaPacienteChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NombrePaciente
        {
            get
            {
                return _NombrePaciente;
            }
            set
            {
                OnNombrePacienteChanging(value);
                ReportPropertyChanging("NombrePaciente");
                _NombrePaciente = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NombrePaciente");
                OnNombrePacienteChanged();
            }
        }
        private global::System.String _NombrePaciente;
        partial void OnNombrePacienteChanging(global::System.String value);
        partial void OnNombrePacienteChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ApellidoPaciente
        {
            get
            {
                return _ApellidoPaciente;
            }
            set
            {
                OnApellidoPacienteChanging(value);
                ReportPropertyChanging("ApellidoPaciente");
                _ApellidoPaciente = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ApellidoPaciente");
                OnApellidoPacienteChanged();
            }
        }
        private global::System.String _ApellidoPaciente;
        partial void OnApellidoPacienteChanging(global::System.String value);
        partial void OnApellidoPacienteChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String contrasena
        {
            get
            {
                return _contrasena;
            }
            set
            {
                OncontrasenaChanging(value);
                ReportPropertyChanging("contrasena");
                _contrasena = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("contrasena");
                OncontrasenaChanged();
            }
        }
        private global::System.String _contrasena;
        partial void OncontrasenaChanging(global::System.String value);
        partial void OncontrasenaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime anionacimiento
        {
            get
            {
                return _anionacimiento;
            }
            set
            {
                OnanionacimientoChanging(value);
                ReportPropertyChanging("anionacimiento");
                _anionacimiento = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("anionacimiento");
                OnanionacimientoChanged();
            }
        }
        private global::System.DateTime _anionacimiento;
        partial void OnanionacimientoChanging(global::System.DateTime value);
        partial void OnanionacimientoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> telefono
        {
            get
            {
                return _telefono;
            }
            set
            {
                OntelefonoChanging(value);
                ReportPropertyChanging("telefono");
                _telefono = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("telefono");
                OntelefonoChanged();
            }
        }
        private Nullable<global::System.Int32> _telefono;
        partial void OntelefonoChanging(Nullable<global::System.Int32> value);
        partial void OntelefonoChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ClinicaAspModel", "FK__Cita__CedulaPaci__0CBAE877", "Cita")]
        public EntityCollection<Cita> Citas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Cita>("ClinicaAspModel.FK__Cita__CedulaPaci__0CBAE877", "Cita");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Cita>("ClinicaAspModel.FK__Cita__CedulaPaci__0CBAE877", "Cita", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
