//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region Metadatos de relaciones en EDM

[assembly: EdmRelationshipAttribute("ClinicaAspModel", "FK__Cita__CedulaM__0DAF0CB0", "Medicos", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Clinica_ASP.Medicos), "Citas", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Clinica_ASP.Citas), true)]
[assembly: EdmRelationshipAttribute("ClinicaAspModel", "FK__Cita__CedulaPaci__0CBAE877", "Pacientes", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Clinica_ASP.Pacientes), "Citas", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Clinica_ASP.Citas), true)]
[assembly: EdmRelationshipAttribute("ClinicaAspModel", "FK__FormulaMe__IdCit__1273C1CD", "Citas", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Clinica_ASP.Citas), "FormulaMedicas", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Clinica_ASP.FormulaMedicas), true)]

#endregion

namespace Clinica_ASP
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class ClinicaAspEntities : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto ClinicaAspEntities usando la cadena de conexión encontrada en la sección 'ClinicaAspEntities' del archivo de configuración de la aplicación.
        /// </summary>
        public ClinicaAspEntities() : base("name=ClinicaAspEntities", "ClinicaAspEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto ClinicaAspEntities.
        /// </summary>
        public ClinicaAspEntities(string connectionString) : base(connectionString, "ClinicaAspEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto ClinicaAspEntities.
        /// </summary>
        public ClinicaAspEntities(EntityConnection connection) : base(connection, "ClinicaAspEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Citas> Citas
        {
            get
            {
                if ((_Citas == null))
                {
                    _Citas = base.CreateObjectSet<Citas>("Citas");
                }
                return _Citas;
            }
        }
        private ObjectSet<Citas> _Citas;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<FormulaMedicas> FormulaMedicas
        {
            get
            {
                if ((_FormulaMedicas == null))
                {
                    _FormulaMedicas = base.CreateObjectSet<FormulaMedicas>("FormulaMedicas");
                }
                return _FormulaMedicas;
            }
        }
        private ObjectSet<FormulaMedicas> _FormulaMedicas;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Medicos> Medicos
        {
            get
            {
                if ((_Medicos == null))
                {
                    _Medicos = base.CreateObjectSet<Medicos>("Medicos");
                }
                return _Medicos;
            }
        }
        private ObjectSet<Medicos> _Medicos;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Pacientes> Pacientes
        {
            get
            {
                if ((_Pacientes == null))
                {
                    _Pacientes = base.CreateObjectSet<Pacientes>("Pacientes");
                }
                return _Pacientes;
            }
        }
        private ObjectSet<Pacientes> _Pacientes;

        #endregion

        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Citas. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToCitas(Citas citas)
        {
            base.AddObject("Citas", citas);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet FormulaMedicas. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToFormulaMedicas(FormulaMedicas formulaMedicas)
        {
            base.AddObject("FormulaMedicas", formulaMedicas);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Medicos. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToMedicos(Medicos medicos)
        {
            base.AddObject("Medicos", medicos);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Pacientes. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToPacientes(Pacientes pacientes)
        {
            base.AddObject("Pacientes", pacientes);
        }

        #endregion

    }

    #endregion

    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ClinicaAspModel", Name="Citas")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Citas : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Citas.
        /// </summary>
        /// <param name="idCita">Valor inicial de la propiedad IdCita.</param>
        /// <param name="fechacita">Valor inicial de la propiedad fechacita.</param>
        /// <param name="horaCita">Valor inicial de la propiedad HoraCita.</param>
        public static Citas CreateCitas(global::System.Int32 idCita, global::System.String fechacita, global::System.String horaCita)
        {
            Citas citas = new Citas();
            citas.IdCita = idCita;
            citas.fechacita = fechacita;
            citas.HoraCita = horaCita;
            return citas;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdCita
        {
            get
            {
                return _IdCita;
            }
            set
            {
                if (_IdCita != value)
                {
                    OnIdCitaChanging(value);
                    ReportPropertyChanging("IdCita");
                    _IdCita = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdCita");
                    OnIdCitaChanged();
                }
            }
        }
        private global::System.Int32 _IdCita;
        partial void OnIdCitaChanging(global::System.Int32 value);
        partial void OnIdCitaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CedulaPaciente
        {
            get
            {
                return _CedulaPaciente;
            }
            set
            {
                OnCedulaPacienteChanging(value);
                ReportPropertyChanging("CedulaPaciente");
                _CedulaPaciente = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CedulaPaciente");
                OnCedulaPacienteChanged();
            }
        }
        private Nullable<global::System.Int32> _CedulaPaciente;
        partial void OnCedulaPacienteChanging(Nullable<global::System.Int32> value);
        partial void OnCedulaPacienteChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CedulaM
        {
            get
            {
                return _CedulaM;
            }
            set
            {
                OnCedulaMChanging(value);
                ReportPropertyChanging("CedulaM");
                _CedulaM = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CedulaM");
                OnCedulaMChanged();
            }
        }
        private Nullable<global::System.Int32> _CedulaM;
        partial void OnCedulaMChanging(Nullable<global::System.Int32> value);
        partial void OnCedulaMChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String fechacita
        {
            get
            {
                return _fechacita;
            }
            set
            {
                OnfechacitaChanging(value);
                ReportPropertyChanging("fechacita");
                _fechacita = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("fechacita");
                OnfechacitaChanged();
            }
        }
        private global::System.String _fechacita;
        partial void OnfechacitaChanging(global::System.String value);
        partial void OnfechacitaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String HoraCita
        {
            get
            {
                return _HoraCita;
            }
            set
            {
                OnHoraCitaChanging(value);
                ReportPropertyChanging("HoraCita");
                _HoraCita = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("HoraCita");
                OnHoraCitaChanged();
            }
        }
        private global::System.String _HoraCita;
        partial void OnHoraCitaChanging(global::System.String value);
        partial void OnHoraCitaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Descripcion
        {
            get
            {
                return _Descripcion;
            }
            set
            {
                OnDescripcionChanging(value);
                ReportPropertyChanging("Descripcion");
                _Descripcion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Descripcion");
                OnDescripcionChanged();
            }
        }
        private global::System.String _Descripcion;
        partial void OnDescripcionChanging(global::System.String value);
        partial void OnDescripcionChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ClinicaAspModel", "FK__Cita__CedulaM__0DAF0CB0", "Medicos")]
        public Medicos Medicos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Medicos>("ClinicaAspModel.FK__Cita__CedulaM__0DAF0CB0", "Medicos").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Medicos>("ClinicaAspModel.FK__Cita__CedulaM__0DAF0CB0", "Medicos").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Medicos> MedicosReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Medicos>("ClinicaAspModel.FK__Cita__CedulaM__0DAF0CB0", "Medicos");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Medicos>("ClinicaAspModel.FK__Cita__CedulaM__0DAF0CB0", "Medicos", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ClinicaAspModel", "FK__Cita__CedulaPaci__0CBAE877", "Pacientes")]
        public Pacientes Pacientes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Pacientes>("ClinicaAspModel.FK__Cita__CedulaPaci__0CBAE877", "Pacientes").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Pacientes>("ClinicaAspModel.FK__Cita__CedulaPaci__0CBAE877", "Pacientes").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Pacientes> PacientesReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Pacientes>("ClinicaAspModel.FK__Cita__CedulaPaci__0CBAE877", "Pacientes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Pacientes>("ClinicaAspModel.FK__Cita__CedulaPaci__0CBAE877", "Pacientes", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ClinicaAspModel", "FK__FormulaMe__IdCit__1273C1CD", "FormulaMedicas")]
        public EntityCollection<FormulaMedicas> FormulaMedicas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<FormulaMedicas>("ClinicaAspModel.FK__FormulaMe__IdCit__1273C1CD", "FormulaMedicas");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<FormulaMedicas>("ClinicaAspModel.FK__FormulaMe__IdCit__1273C1CD", "FormulaMedicas", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ClinicaAspModel", Name="FormulaMedicas")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class FormulaMedicas : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto FormulaMedicas.
        /// </summary>
        /// <param name="idFormulaMedica">Valor inicial de la propiedad IdFormulaMedica.</param>
        /// <param name="idCita">Valor inicial de la propiedad IdCita.</param>
        /// <param name="recetaMedica">Valor inicial de la propiedad RecetaMedica.</param>
        public static FormulaMedicas CreateFormulaMedicas(global::System.Int32 idFormulaMedica, global::System.Int32 idCita, global::System.String recetaMedica)
        {
            FormulaMedicas formulaMedicas = new FormulaMedicas();
            formulaMedicas.IdFormulaMedica = idFormulaMedica;
            formulaMedicas.IdCita = idCita;
            formulaMedicas.RecetaMedica = recetaMedica;
            return formulaMedicas;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdFormulaMedica
        {
            get
            {
                return _IdFormulaMedica;
            }
            set
            {
                if (_IdFormulaMedica != value)
                {
                    OnIdFormulaMedicaChanging(value);
                    ReportPropertyChanging("IdFormulaMedica");
                    _IdFormulaMedica = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdFormulaMedica");
                    OnIdFormulaMedicaChanged();
                }
            }
        }
        private global::System.Int32 _IdFormulaMedica;
        partial void OnIdFormulaMedicaChanging(global::System.Int32 value);
        partial void OnIdFormulaMedicaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdCita
        {
            get
            {
                return _IdCita;
            }
            set
            {
                OnIdCitaChanging(value);
                ReportPropertyChanging("IdCita");
                _IdCita = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdCita");
                OnIdCitaChanged();
            }
        }
        private global::System.Int32 _IdCita;
        partial void OnIdCitaChanging(global::System.Int32 value);
        partial void OnIdCitaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RecetaMedica
        {
            get
            {
                return _RecetaMedica;
            }
            set
            {
                OnRecetaMedicaChanging(value);
                ReportPropertyChanging("RecetaMedica");
                _RecetaMedica = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("RecetaMedica");
                OnRecetaMedicaChanged();
            }
        }
        private global::System.String _RecetaMedica;
        partial void OnRecetaMedicaChanging(global::System.String value);
        partial void OnRecetaMedicaChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ClinicaAspModel", "FK__FormulaMe__IdCit__1273C1CD", "Citas")]
        public Citas Citas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Citas>("ClinicaAspModel.FK__FormulaMe__IdCit__1273C1CD", "Citas").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Citas>("ClinicaAspModel.FK__FormulaMe__IdCit__1273C1CD", "Citas").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Citas> CitasReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Citas>("ClinicaAspModel.FK__FormulaMe__IdCit__1273C1CD", "Citas");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Citas>("ClinicaAspModel.FK__FormulaMe__IdCit__1273C1CD", "Citas", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ClinicaAspModel", Name="Medicos")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Medicos : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Medicos.
        /// </summary>
        /// <param name="cedulaM">Valor inicial de la propiedad CedulaM.</param>
        /// <param name="nombreM">Valor inicial de la propiedad NombreM.</param>
        /// <param name="apellidoM">Valor inicial de la propiedad ApellidoM.</param>
        /// <param name="emailM">Valor inicial de la propiedad EmailM.</param>
        /// <param name="contrasena">Valor inicial de la propiedad contrasena.</param>
        /// <param name="anionacimiento">Valor inicial de la propiedad anionacimiento.</param>
        /// <param name="especialidad">Valor inicial de la propiedad Especialidad.</param>
        public static Medicos CreateMedicos(global::System.Int32 cedulaM, global::System.String nombreM, global::System.String apellidoM, global::System.String emailM, global::System.String contrasena, global::System.DateTime anionacimiento, global::System.String especialidad)
        {
            Medicos medicos = new Medicos();
            medicos.CedulaM = cedulaM;
            medicos.NombreM = nombreM;
            medicos.ApellidoM = apellidoM;
            medicos.EmailM = emailM;
            medicos.contrasena = contrasena;
            medicos.anionacimiento = anionacimiento;
            medicos.Especialidad = especialidad;
            return medicos;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CedulaM
        {
            get
            {
                return _CedulaM;
            }
            set
            {
                if (_CedulaM != value)
                {
                    OnCedulaMChanging(value);
                    ReportPropertyChanging("CedulaM");
                    _CedulaM = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CedulaM");
                    OnCedulaMChanged();
                }
            }
        }
        private global::System.Int32 _CedulaM;
        partial void OnCedulaMChanging(global::System.Int32 value);
        partial void OnCedulaMChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NombreM
        {
            get
            {
                return _NombreM;
            }
            set
            {
                OnNombreMChanging(value);
                ReportPropertyChanging("NombreM");
                _NombreM = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NombreM");
                OnNombreMChanged();
            }
        }
        private global::System.String _NombreM;
        partial void OnNombreMChanging(global::System.String value);
        partial void OnNombreMChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ApellidoM
        {
            get
            {
                return _ApellidoM;
            }
            set
            {
                OnApellidoMChanging(value);
                ReportPropertyChanging("ApellidoM");
                _ApellidoM = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ApellidoM");
                OnApellidoMChanged();
            }
        }
        private global::System.String _ApellidoM;
        partial void OnApellidoMChanging(global::System.String value);
        partial void OnApellidoMChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EmailM
        {
            get
            {
                return _EmailM;
            }
            set
            {
                OnEmailMChanging(value);
                ReportPropertyChanging("EmailM");
                _EmailM = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("EmailM");
                OnEmailMChanged();
            }
        }
        private global::System.String _EmailM;
        partial void OnEmailMChanging(global::System.String value);
        partial void OnEmailMChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String contrasena
        {
            get
            {
                return _contrasena;
            }
            set
            {
                OncontrasenaChanging(value);
                ReportPropertyChanging("contrasena");
                _contrasena = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("contrasena");
                OncontrasenaChanged();
            }
        }
        private global::System.String _contrasena;
        partial void OncontrasenaChanging(global::System.String value);
        partial void OncontrasenaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime anionacimiento
        {
            get
            {
                return _anionacimiento;
            }
            set
            {
                OnanionacimientoChanging(value);
                ReportPropertyChanging("anionacimiento");
                _anionacimiento = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("anionacimiento");
                OnanionacimientoChanged();
            }
        }
        private global::System.DateTime _anionacimiento;
        partial void OnanionacimientoChanging(global::System.DateTime value);
        partial void OnanionacimientoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> telefono
        {
            get
            {
                return _telefono;
            }
            set
            {
                OntelefonoChanging(value);
                ReportPropertyChanging("telefono");
                _telefono = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("telefono");
                OntelefonoChanged();
            }
        }
        private Nullable<global::System.Int32> _telefono;
        partial void OntelefonoChanging(Nullable<global::System.Int32> value);
        partial void OntelefonoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Especialidad
        {
            get
            {
                return _Especialidad;
            }
            set
            {
                OnEspecialidadChanging(value);
                ReportPropertyChanging("Especialidad");
                _Especialidad = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Especialidad");
                OnEspecialidadChanged();
            }
        }
        private global::System.String _Especialidad;
        partial void OnEspecialidadChanging(global::System.String value);
        partial void OnEspecialidadChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ClinicaAspModel", "FK__Cita__CedulaM__0DAF0CB0", "Citas")]
        public EntityCollection<Citas> Citas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Citas>("ClinicaAspModel.FK__Cita__CedulaM__0DAF0CB0", "Citas");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Citas>("ClinicaAspModel.FK__Cita__CedulaM__0DAF0CB0", "Citas", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ClinicaAspModel", Name="Pacientes")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Pacientes : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Pacientes.
        /// </summary>
        /// <param name="cedulaPaciente">Valor inicial de la propiedad CedulaPaciente.</param>
        /// <param name="nombrePaciente">Valor inicial de la propiedad NombrePaciente.</param>
        /// <param name="apellidoPaciente">Valor inicial de la propiedad ApellidoPaciente.</param>
        /// <param name="email">Valor inicial de la propiedad Email.</param>
        /// <param name="contrasena">Valor inicial de la propiedad contrasena.</param>
        /// <param name="anionacimiento">Valor inicial de la propiedad anionacimiento.</param>
        public static Pacientes CreatePacientes(global::System.Int32 cedulaPaciente, global::System.String nombrePaciente, global::System.String apellidoPaciente, global::System.String email, global::System.String contrasena, global::System.DateTime anionacimiento)
        {
            Pacientes pacientes = new Pacientes();
            pacientes.CedulaPaciente = cedulaPaciente;
            pacientes.NombrePaciente = nombrePaciente;
            pacientes.ApellidoPaciente = apellidoPaciente;
            pacientes.Email = email;
            pacientes.contrasena = contrasena;
            pacientes.anionacimiento = anionacimiento;
            return pacientes;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CedulaPaciente
        {
            get
            {
                return _CedulaPaciente;
            }
            set
            {
                if (_CedulaPaciente != value)
                {
                    OnCedulaPacienteChanging(value);
                    ReportPropertyChanging("CedulaPaciente");
                    _CedulaPaciente = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CedulaPaciente");
                    OnCedulaPacienteChanged();
                }
            }
        }
        private global::System.Int32 _CedulaPaciente;
        partial void OnCedulaPacienteChanging(global::System.Int32 value);
        partial void OnCedulaPacienteChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NombrePaciente
        {
            get
            {
                return _NombrePaciente;
            }
            set
            {
                OnNombrePacienteChanging(value);
                ReportPropertyChanging("NombrePaciente");
                _NombrePaciente = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NombrePaciente");
                OnNombrePacienteChanged();
            }
        }
        private global::System.String _NombrePaciente;
        partial void OnNombrePacienteChanging(global::System.String value);
        partial void OnNombrePacienteChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ApellidoPaciente
        {
            get
            {
                return _ApellidoPaciente;
            }
            set
            {
                OnApellidoPacienteChanging(value);
                ReportPropertyChanging("ApellidoPaciente");
                _ApellidoPaciente = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ApellidoPaciente");
                OnApellidoPacienteChanged();
            }
        }
        private global::System.String _ApellidoPaciente;
        partial void OnApellidoPacienteChanging(global::System.String value);
        partial void OnApellidoPacienteChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String contrasena
        {
            get
            {
                return _contrasena;
            }
            set
            {
                OncontrasenaChanging(value);
                ReportPropertyChanging("contrasena");
                _contrasena = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("contrasena");
                OncontrasenaChanged();
            }
        }
        private global::System.String _contrasena;
        partial void OncontrasenaChanging(global::System.String value);
        partial void OncontrasenaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime anionacimiento
        {
            get
            {
                return _anionacimiento;
            }
            set
            {
                OnanionacimientoChanging(value);
                ReportPropertyChanging("anionacimiento");
                _anionacimiento = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("anionacimiento");
                OnanionacimientoChanged();
            }
        }
        private global::System.DateTime _anionacimiento;
        partial void OnanionacimientoChanging(global::System.DateTime value);
        partial void OnanionacimientoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> telefono
        {
            get
            {
                return _telefono;
            }
            set
            {
                OntelefonoChanging(value);
                ReportPropertyChanging("telefono");
                _telefono = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("telefono");
                OntelefonoChanged();
            }
        }
        private Nullable<global::System.Int32> _telefono;
        partial void OntelefonoChanging(Nullable<global::System.Int32> value);
        partial void OntelefonoChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ClinicaAspModel", "FK__Cita__CedulaPaci__0CBAE877", "Citas")]
        public EntityCollection<Citas> Citas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Citas>("ClinicaAspModel.FK__Cita__CedulaPaci__0CBAE877", "Citas");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Citas>("ClinicaAspModel.FK__Cita__CedulaPaci__0CBAE877", "Citas", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
